# -*- coding: utf-8 -*-
from . import coop_security_unfreeze
from . import coop_legal_form
from . import coop_specialization
from . import coop_verification
from . import res_partner
from . import res_users
from . import coop_power
from . import coop_page
from . import coop_membership
from . import coop_menu_order
from . import coop_setup
from . import coop_notification
from . import coop_notification_pref
from . import coop_block
from . import coop_admit_wizard
from . import coop_favorite
from . import coop_contact_line
from . import coop_membership_role
